### ISSUE TITLE
Technische Fragen des Antrags: offene Punkte

### ISSUE THREAD

**Issue by ghost** [money-infrastructure/doku#10]
deleted

**Comment by hfhoyer** [comment]
Ist überhaupt eine NMI Coin geplant? 
So wie ich es verstehe, gerade nicht.

**Comment by Paul-Zehle** [comment]
Die Formulierung "coin" habe ich benutzt, weil es möglich sein soll, innerhalb der NMI Bezahlungen abzuwickeln und ich das in dem Kontext als "coin" verstehe.

Aus der [Projektbeschreibung](https://github.com/money-infrastructure/doku/blob/master/Deutsch/Neue_Geldinfrastruktur-Projektbeschreibung.pdf)
"Das Projekt Neue Geldinfrastruktur hat das Ziel eine globale und dezentrale Krytogeld-Infrastruktur
für den Zahlungsverkehr und andere Finanzdienste sowie für Finanzprodukte zu errichten."
"Sie ist speziell für klassische Währung gemacht und wandelt z.B. Euros in Vollgeld-Krypto-Euros um."

Der Begriff "Vollgeld-Krypto-Euro" ist für mich frei übersetzt ein Crypto-Coin.

**Comment by Arne-Pfeilsticker** [comment]
Hallo Paul,
hast du die überarbeitete Version der Projektbeschreibung gelesen? (Siehe Verzeichnis Deutsch oder English) Vielleicht sollten wir für unser nächstes Arbeitstreffen den genauen Ablauf der von dir angesprochenen Punkte zum Thema machen.

Hier ein paar Anmerkungen zu dem von dir angesprochenen Szenario:

> 1. Bob tauscht 10.000 Euro über die GLS-Bank in NMI-coins um.

In der NMI gibt es keine "coins", sondern Konten, die in einer Baumstruktur zusammengefasst sind.

Der auf einem Eurokonto ausgewiesene Betrag weist eine Forderung gegen die Zentralbank nach.
Entweder direkt, wenn die Zentralbank mitspielt, oder über ein Treuhandvermögen, wenn eine gemeinnützige Bank dazwischen geschaltet ist.

Diese Treuhandvermögen ist eine Barreserve, d.h. Zentralbankgeld, das von der Bank verwaltet wird, aber im Eigentum der jeweiligen NMI-Kontoinhaber steht.

> 2. Die Zentralbank sichert Bob zu, dass seine Euro nun auf einem Zentralbankkonto liegen und seine NMI-coins zu 100% gedeckt sind.

Das Geld in der NMI ist nicht zu 100% gedeckt, sondern ist 100%iges Zentralbankgiralgeld. Es ist Geld, das auf einem "Sammelkonto" bei der Zentralbank liegt. Das ist vergleichbar mit Bargeld. Hier gibt es die Position "Bargeld im Umlauf". Die Bundesbank weiß zwar wieviel Bargeld im Umlauf ist, aber sie weiß nicht wer gerade das Bargeld hat.  

Das Geld in der NMI ist digital verbrieftes Zentralbankgeld, über das mit kryptographischen Schlüsseln verfügt werden kann.

> 3. Die GLS-Bank wird gehackt und die private keys missbraucht, um neue, ungedeckte NMI-coins zu erschaffen, was nach und nach bekannt wird. (Das ist nur eines von mehreren realistischen Szenarien, das eingeplant werden muss. Siehe SWIFT-Hacks.)

Wenn die GLS-Bank gehackt werden würde, dann wäre es für die NMI kein Beinbruch.
1. Die privaten Keys der NMI-Nutzer hat nur der Nutzer.
2. Ein Hacker könnte kein neues NMI-Geld schaffen, weil die Kontoführung der Barreserve bei der Zentralbank liegt.
3. Um Geld in die NMI zu bekommen muss bei der Zentralbank eine Überweisung von einem anderen Zentralbankkonto auf das Konto "Kryptogeld im Umlauf" oder auf das Treuhandkonto bei der Zentralbank erfolgen.

> 4. Bob will nun mit seinen NMI-coins einen Gebrauchtwagen von Alice kaufen.
> 5. Alice lehnt das ab, weil die Bewertung der GLS-Bank mittlerweile auf "nicht vertrauenswürdig" gefallen ist.

Ein Treuhandvermögen gehört nicht zum Eigentum des Treuhänders und fällt auch nicht in die Insolvenzmasse. Der Treuhandvertrag mit der GLS-Bank wäre so zu regeln, dass im Falle einer Insolvenz auftomatisch ein vorher bestimmter anderer Treuhänder (= andere Bank) einspringt, die die Geschäfte fortführt.

Bob könnte jederzeit bei der anderen Bank sein Geld in der NMI auf ein Konto der neuen Bank zur Barauszahlung überweisen und das Geld bar abheben und damit Alice bezahlen.

**Comment by Arne-Pfeilsticker** [comment]
> Der Begriff "Vollgeld-Krypto-Euro" ist für mich frei übersetzt ein Crypto-Coin.

Vollgeld-Krypto-Euros in der NMI sind keine Coins, wie z.B. in anderen Kryptowährungen, sondern eine Forderung gegen die Zentralbank.

In der NMI werden keine Coins verwaltet, sondern die Konten in der NMI sind der "Einzelnachweis" für Geld auf einem Zentralbankgirokonto.

**Comment by Paul-Zehle** [comment]
Hallo Arne,

ja ich habe die überarbeitete Version gelesen und in der Antwort an Hans-Florian verlinkt.
Bei der Formulierung "Kryptogeld-Infrastruktur" und meinem Background habe ich den Begriff "coin" wohl etwas vorschnell verwendet.

Bliebe der Angriffsvektor nicht dennoch gleich, wenn auch mit einer anderen Auswirkung?

> Um Geld in die NMI zu bekommen muss bei der Zentralbank eine Überweisung von einem anderen Zentralbankkonto auf das Konto "Kryptogeld im Umlauf" oder auf das Treuhandkonto bei der Zentralbank erfolgen.

Eine Einzahlung auf ein NMI-Konto würde doch, unabhängig von der Akzeptanz der Zentralbank, seitens der Privatbanken erfolgen, die sicher stellen müssen, dass die Überweisung von Zentralbankkonto zum Zentralbank-"Sammelkonto" auch tatsächlich getätigt wurde, richtig?

An dieser Stelle sehe ich die reale Gefahr, dass der Mechanismus missbraucht werden kann.
Auch wenn Bob weiterhin ohne Probleme bezahlen kann, könnte plötzlich mehr Kryptovollgeld im Umlauf kommen, als auf dem Zentralbank-"Sammelkonto" läge. Die Zentralbankbank könnte das schlecht nachvollziehen, da die NMI-Konten dezentral geführt werden sollen. Es gäbe nach meinem jetzigen Verständnis keinen automatisierten Mechanismus, der das verhindern oder aufdecken würde. Zumindest hatten wir darüber noch nicht gesprochen.

In diesem Sinne gälte die Aussage
> Das Geld in der NMI ist nicht zu 100% gedeckt, sondern ist 100%iges Zentralbankgiralgeld.
nicht mehr.

**Comment by Arne-Pfeilsticker** [comment]
Paul, die ganzen Schutzmechanismen sind noch nicht bis ins Detail spezifiziert. Daher bin ich dir dankbar, wenn du nach Schwachstellen suchst.

Ein Punkt sollte klar sein, dass derjenige, der über einen privaten Schlüssel verfügt, der hat die Voraussetzung, um über die damit verbundenen Rechte und Verfahren zu verfügen. 

Um sicher zu stellen, dass nur der Berechtigte über einen privaten Schlüssel verfügt, sind zusätzliche Schutzmechanismen angedacht, die je nach Schutzbedürfnis einzeln oder im Verbund zusätzlich eingeführt werden sollen:

1.  Biometrische Kontrollen
1. Einschränkung des Prozesses, der die Buchungen aus und in die NMI macht, auf ganz bestimmte Hardware und in einem ganz bestimmten Zeitfenster.
1. Zahlungen in die NMI müssen von einer anderen Person freigegeben werden als Zahlungen aus der NMI, aber sie können zum Schluss nur zusammen verarbeitet werden.
1. Dieser Prozess muss durch mehrere Personen freigegeben werden.
1. Die Signatur muss eine sog. [qualifizierte elektronische Signatur](https://de.wikipedia.org/wiki/Qualifizierte_elektronische_Signatur) sein.
1. usw.

> Eine Einzahlung bzw. Gutschrift auf ein NMI-Konto würde doch, unabhängig von der Akzeptanz der Zentralbank, seitens der Privatbanken erfolgen, die sicher stellen müssen, dass die Überweisung von Zentralbankkonto zum Zentralbank-"Sammelkonto" auch tatsächlich getätigt wurde, richtig?

Nein. Kontoführende Stelle für die Barreserve (= Zentralbankkonto) ist die Zentralbank. Auf diesem Konto würde eine Gutschrift für ein NMI-Konto eingehen, die dann auf dem Kontoauszug der Zentralbank erscheint und digital an die Privatbank übermittelt wird.  Diese Daten werden von einer Person als ganzes zur Verarbeitung frei gegeben und von einer anderen Person automatisiert verarbeitet. Dieser Schritt führt zu einer oder mehreren Gutschriften auf den Empfängerkonten in der NMI.

Selbst wenn eine Zahlung illegal in die NMI eingeschleust werden könnte, könnte die Spur des Geldes detailliert im System und auch wieder nach außen auf ein anderes Konto einer Geschäftsbank verfolgt werden. Diese Spur könnte für eine strafrechtliche Verfolgung herangezogen werden.

> Auch wenn Bob weiterhin ohne Probleme bezahlen kann, könnte plötzlich mehr Kryptovollgeld in Umlauf kommen, als auf dem Zentralbank-"Sammelkonto" läge. 

Auf dem Identitäten-Server wird der Status einer Blockchain und damit eines einzelnen Kontos gespeichert. Es wäre möglich, dass dieser Status auch den Kontostand enthält. Dadurch wäre es möglich auf dem Identitäten-Server den Gesamtsaldo z.B. der Eurokonten anzuzeigen, der dann mit dem Saldo der Barreserve übereinstimmen muss.

**Comment by Paul-Zehle** [comment]
Hallo Arne,

eines verstehe ich nicht und das ist auch der Grund, der mich davon hat ausgehen lassen, die NMI ist eine Kryptowährung:

- Bitcoin ist eine Kryptowährung, was die NMI nicht ist und auch nicht sein will. Der Begriff "digitales Vollgeld" statt "Kryptovollgeld" wäre dann passender und weniger missverständlich.
- Bitcoin verfügt über den Proof-of-Work-Konsensmechanismus, was zu dem kritisierten hohen Stromverbrauch führt. Die NMI verfügt für die Vollgeld-Zu- und -Abflüsse aber über keinen Konsensmechanismus, benötigt daher logischerweise auch keinen hohen Stromverbrauch.
- Da kommuniziert wird, die NMI leiste mehr als der Proof-of-Work-Konsensmechanismus und das bei weitaus niedrigerem Stromverbauch, lässt es den technisch versierten Leser vermuten, die NMI böte einen neuen, bahnbrechenden Konsensmechanismus. Bei genauer Betrachtung stellt sich diese Annahme allerdings als falsch heraus. Der Konsens betrifft die Transaktionen/Verträge, nicht aber das Ganze, inklusive der Zu- und Abflüsse (beim Bitcoin das Mining), was Bitcoin's Proof-of-Work-Konsensmechanismus leistet.
- Bitcoin stellt keine Möglichkeit für Smart Contracts zu Verfügung, die NMI aber schon.

Mir ist jetzt klar, dass die NMI keinen Konsensmechanismus für die Zu- und Abflüsse des Vollgeldes vorsehen will.
Die Vergleiche zum Bitcoin und die Kritik desselben, gepaart mit der Aussage, die NMI leiste mehr, führt jemanden wie mich, der sich im Vorfeld mit Kryptowährungen beschäftigt hat, allerdings leicht in die Irre. 
Vielleicht wäre es hilfreich, sich noch einmal Gedanken über diese Strategie zu machen?
Einige der benutzten Fachbegriffe bringen in der Fachwelt fest definierte Implikationen mit sich, die auf die NMI nicht zutreffen. Es wäre schade, wenn das als Auslöser genommen würde die NMI zu kritisieren, anstatt den Fokus auf dem eigentlichen Ziel zu halten.

**Comment by Arne-Pfeilsticker** [comment]
> Bitcoin ist eine Kryptowährung, was die NMI nicht ist und auch nicht sein will. Der Begriff "digitales Vollgeld" statt "Kryptovollgeld" wäre dann passender und weniger missverständlich.

Hallo Paul, Geld auf einem Girokonto bei der Zentralbank ist digitales Vollgeld, aber kein Krypto-
 Vollgeld.

Wenn du zwischen der Verpackung und dem Inhalt unterscheidest, dann löst sich mache Frage ganz einfach auf. Bei Rechten im allgemeinen und auch beim Geld ist die "Verpackung" die Art und Weise wie ein Recht (= Inhalt) nachgewiesen wird. 

Du kannst das Ganze auch mit deinem Personalausweis (= Nachweis) und dir, der in diesem Ausweis nachgewiesenen Person, vergleichen. Auch du und dein Personalausweis sind zwei sehr unterschiedliche Dinge. Stell dir weiter vor, dass du dein Personalausweis wie ein Namensschild trägst, aber du selbst unsichtbar wärst, aber nach wie vor so handeln könnest wie du handelst, dann wären all denjenigen, die den Zusammenhang nicht kennen, ziemlich verwirrt und würden deinem Personalausweis geradezu magische Kräfte zusprechen. 

Und genau das ist die Situation beim Geld: Der Nachweis für Geld wird mit dem eigentlichen Geld verwechselt, das ein sog. subjektives Recht ist. Und Rechte sind zwar real, aber dennoch unsichtbare abstrakte Beziehungen zwischen Personen.

Kryptogeld ist also Geld, das mit Hilfe kryptographischer Methoden digital in einer Blockchain nachgewiesen wird.

Der Inhalt, das eigentliche Geld, ist bei Bitcoin ein Eigentumsrecht an bestimmten Daten in der Blockchain. In der NMI ist das Geld genauso wie Bargeld ein Forderung gegen die Zentralbank.

Die NMI ist ein System, in dem natürliche und juristische Personen nicht nur Geld, sonder beliebige Rechte und Pflichten selbst verwalten können. Die NMI will ganz bewußt keine eigenes Geld schaffen, sondern eine alternative Form des Nachweises für vorhandenes Geld bieten.

Über 90% aller Zahlungen werden wertmäßig mit dem von Geschäftsbanken geschaffenem Geld geleistet und für dieses Geld streichen die Geschäftsbanken den Geldschöpfungsgewinn ein. Wenn dieses Geschäftsbankengeld auf ein Konto in der NMI überwiesen wird, dann muss die Geschäftsbank diese Überweisung mit Zentralbankgeld bezahlen und aus dem privaten Geschäftsbankengeld wird Vollgeld und ab diesem Zeitpunkt fließt der Geldschöpfungsgewinn der Allgemeinheit zu.

> Bitcoin verfügt über den Proof-of-Work-Konsensmechanismus, was zu dem kritisierten hohen Stromverbrauch führt. Die NMI verfügt für die Vollgeld-Zu- und -Abflüsse aber über keinen Konsensmechanismus, benötigt daher logischerweise auch keinen hohen Stromverbrauch.

Der praktische Sinn und Zweck der unterschiedlichen Konsensmechanismen in Kryptowährungen besteht darin, dass in einem dezentralen System ohne Treuhänder nicht geschummelt wird. Ohne diese Konsensmechanismen könnte ein Nutzer z.B. sein Geld mehrfach ausgeben.

> Da kommuniziert wird, die NMI leiste mehr als der Proof-of-Work-Konsensmechanismus und das bei weitaus niedrigerem Stromverbauch, lässt es den technisch versierten Leser vermuten, die NMI böte einen neuen, bahnbrechenden Konsensmechanismus. Bei genauer Betrachtung stellt sich diese Annahme allerdings als falsch heraus. Der Konsens betrifft die Transaktionen/Verträge, nicht aber das Ganze, inklusive der Zu- und Abflüsse (beim Bitcoin das Mining), was Bitcoin's Proof-of-Work-Konsensmechanismus leistet.

In der NMI gibt es ebenfalls einen Konsensmechanismus, den ich früher "inverses" und nach verschiedenen Einwänden "rechtliches" Konsensieren nenne. Dieser Konsensmechanismus benötigt keinerlei Strom, weil er nicht wie die derzeitigen Konsensmechanismen das Problem nicht ausschließlich technisch, sondern insbesondere rechtlich löst. 

Zum Konsensmechanismus in der NMI gehört nicht nur das "rechtliche Konsensieren", sondern genau genommen müssen auch noch andere Mechanismen, wie z.B. der Identitäten Server Cluster und die Art und Weise wie Daten bei einem Nutzer gespeichert werden hinzugrerechnet werden.

Details findest du im Kapitel Schlüsselideen in der Projektbeschreibung.

In der NMI werden alle Transaktionen und dazu gehören auch alle Zu- und Abflüsse von Geld in die NMI und aus der NMI über Verträge abgewickelt. Und daher wird wie bei Bitcoin die gesamte Palette abgedeckt. Aber es besteht natürlich ein unterschiedlicher Konsens darüber wie Geld im System entsteht. Bei Bitcoin ist es die Geldschöpfung durch den sog. "block reward", der im Programm fest verankert ist. Bei der NMI gibt es dahingegen keine Geldschöpfung, sondern wie gesagt ist das Geld in der NMI eine Forderung gegen die Zentralbank, die entweder direkt oder indirekt nachgewiesen wird. (Siehe die letzten beiden Grafiken in der Projektbeschreibung.)

Die NMI könnte man sich auch als ein System vorstellen, das den Einzelnachweis für ein bestimmtes Zentralbankkonto durchführt. Das Zentralbankkonto ist sozusagen ein Sammelkonto, bei der die Bundesbank nicht weiß, wem das Geld zu einem bestimmten Zeitpunkt gehört. Das erfährt sie nur dann, wenn der derzeitige Eigentümer, dieses Geld auf ein Konto einer Geschäftsbank überweist.

> Die Vergleiche zum Bitcoin und die Kritik desselben, gepaart mit der Aussage, die NMI leiste mehr, führt jemanden wie mich, der sich im Vorfeld mit Kryptowährungen beschäftigt hat, allerdings leicht in die Irre.

Die Aussage, dass der Konsensmechanismus in der NMI **mehr leistet**, als der _Proof of Work_ bezieht sich darauf, dass der Konsensmechanismus nicht nur das leistet, was seine Aufgabe ist, sondern dabei kein Strom verbraucht, die Skalierung ist nicht von der Anzahl der Nutzer abhängig und Transaktion können in Echtzeit durchgeführt werden. Das sind alles wichtige Punkte, die jeder für sich betrachtet einen echten Mehrwert darstellen.

"Kein Stromverbrauch" bezieht sich nur auf den Konsensmechanismus, weil hier das Problem rechtlich und verfahrenstechnisch so gelöst wird und kein Strom zusätzlich verbraucht wird, der nicht z.B. durch das Speichern und Übertragen der Daten sowieso verbraucht werden würde. 

Würde man bei Bitcoin und der NMI den Konsensmechanismus abschalten, dann würde sich der Stromverbrauch bei Bitcoin drastisch und in der NMI nicht verändern. Selbst ohne Konsensmechanismus wäre im Vergleich zwischen Bitcoin und NMI der Ressourcenverbrauch in der NMI drastisch geringer, weil allein die Nutzerdaten nur ein mal beim Nutzer selbst plus drei Mal als verschlüsseltes Backup bei anderen Nutzern gespeichert werde. Bei Bitcoin müssten eigentlich alle Nutzer die gesamte Blockchain speichern, weil nur so der Anspruch eines dezentralen Systems ohne Treuhänder aufrecht erhalten werden kann. Dazu kommt noch in der NMI habe Daten ein Verfallsdatum und können danach gelöscht werden, bei Bitcoin nicht.
