### ISSUE TITLE
Frage zur Dezentralisierung

### ISSUE THREAD

**Issue by ghost** [money-infrastructure/doku#11]
deleted

**Comment by Arne-Pfeilsticker** [comment]
Der Idenditätenserver ist ein Server-Cluster, der einmal angestoßen unabhängig und dezentral läuft.

NMI-Nutzer können gegen Bezahlung dem Server Resourcen zur Verfügung stellen, die der ID-Server selbständig verwaltet.

Updates der Serverinfrastruktur werden beim Server angemeldet. Der führt dann eine Abstimmung z.B. unter den am Projekt beteiligten Entwicklern durch und wenn die Mehrheit dafür ist, wird das Update in einer Blockchain dokumentiert und installiert. Zur Abstimmung überweisen die Entwickler, die hierfür einen Token erhalten haben, diesen Token auf ein Ja oder Nein-Konto.

Die Vorstellung ist, dass das System basisdemokratisch gesteuert und verwaltet wird. Es wäre auch denkbar, dass hierfür eine gemeinnützige Organisation gegründet wird.
