### ISSUE TITLE
EU Proposal Template

### ISSUE THREAD

**Issue by Arne-Pfeilsticker** [money-infrastructure/doku#12]
If you want to work on this project in a paid job, please take a look at the EU Proposal Template and contact me at short notice.

Of course, I expect those who want a paid job to make a substantial contribution to the preparation of the application.

**Comment by Paul-Zehle** [comment]
Ich bin aufgrund anderer Verpflichtungen zeitlich sehr eingeschränkt, was sich in mittelfristig nicht ändern wird und kann daher nur anbieten, beratend zu unterstützen.
Eine Bezahlung ist für mich nicht ausschlaggebend, die Unterstützung würde ich kostenfrei leisten.
