### ISSUE TITLE
Datenschutz vs. Behördenzugriffe

### ISSUE THREAD

**Issue by ghost** [money-infrastructure/doku#13]
deleted

**Comment by Arne-Pfeilsticker** [comment]
Du sprichst einen wichtigenPunkt an, der noch nicht endgültig entschieden ist.

Ich neige dazu, dass das System so gebaut wird, dass der Datenschutz und die informationelle Selbstbestimmung gewährleistet werden. 

Und das bedeutet in der Tat: Keinen Zugriff auf meine Daten auch nicht durch NSA & Co.

100%tiger Datenschutz bedeutet dies aber dennoch nicht, weil wer immer in den Besitz der privaten Schlüssel kommt und auch noch die zusätzlichen Sicherheitsschranken überwindet, der kann auf die Daten eines Nutzers zugreifen.

In der heutigen Zeit habe ich eher das Gefühl, dass sich die Zivilgesellschaft vor den Übergriffen und der Überwachung durch den Staates geschützt werden muss, als umgekehrt. 

Was wir brauchen ist ein transparenter Staat, aber nicht transparente Bürger.

Viele der pro Überwachungsstaat vorgebrachten Argumente, sind teilweise richtig und sollten auch nicht ignoriert werden.

Was die Eindämmung krimineller Aktivitäten anbelangt, ist m.E. die NMI trotz Datenschutz effizienter, als das derzeitige System, weil aufgrund der ESA-Verträge nicht ohne weiteres Geld hin und her transferiert werden kann. Reine Finanztransaktionen könnten sogar, ab einer bestimmten Höhe - wie derzeit auch von Banken - automatisch an die zuständigen Behörden gemeldet werden. Und bei bestimmten Verträgen bzw. Produkten könnte die ESA-Verträge so gestaltet werden, dass die zuständigen Behörden automatisch "Vertragspartner" werden, um beispielsweise bestimmte Transaktionen zu genehmigen. Und wer Drogen oder Waffen als Hundefutter deklariert, der läuft schnell Gefahr, dass er im System gesperrt wird und nicht mehr über sein Geld verfügen kann, obwohl die Pflichten weiterhin gelten. Und es wäre niemand da, der diese Sperre aufheben könnte.

Was die rechtliche Seite anbelangt, scheint mir die NMI nur schwer fassbar zu sein, weil es keine Treuhänder, wie jetzt die Banken gibt. Und wo keine Bank ist, da kann kein Bankgeheimnis gebrochen werden.

**Comment by Paul-Zehle** [comment]
Was Geheimdienstzugriffe betrifft, stimme ich dir zu. Ebenso was das Ungleichgewicht zwischen fehlender staatlicher Transparenz und der anlasslosen Überwachung der Bürger betrifft.

Liege ich richtig mit der Annahme, dass die NMI für eine erfolgreiche Bewilligung von EU-Fördergeldern im Vorfeld versichern muss, dass alle geltenden EU-Gesetze bzw. Verordnungen eingehalten werden? Oder ist dieser Punkt nachrangig?

Welche Bestimmungen hinsichtlich Geldwäsche und Kontenzugriffe seitens der Ämter und Strafverfolgungsbehörden sind im EU-Recht verankert?
Spielen nationale Gesetze und Bestimmungen überhaupt eine Rolle, wenn sie über den Rahmen, den die EU vorgibt, hinaus gehen?
