### ISSUE TITLE
Einladung virtuelle Arbeitstreffen im Januar und Februar

### ISSUE THREAD

**Issue by Arne-Pfeilsticker** [money-infrastructure/doku#14]
Hiermit lade ich ein zum:
     **4. virtuellen Arbeitstreffen am Freitag, den 19.1.2018 um 19 Uhr
     5. virtuellen Arbeitstreffen am Freitag, den 2.2.2018 um 19 Uhr
     6. virtuellen Arbeitstreffen am Freitag, den 16.2.2018 um 19 Uhr**

Über den Link https://zoom.us/j/292196878 kann an der Sitzung teilgenommen werden. Dieser Link kann jetzt schon getestet werden. 

Tagesordnung:
- Ausarbeitung und Besprechung des Antrag auf Förderung des Projektes durch die EU
- Fragen zum Projekt

Der Antrag kann [hier](https://github.com/money-infrastructure/doku/blob/master/English/EU_Proposal_Part_1.adoc) eingesehen werden. Bitte arbeitet an diesem Antrag mit, denn die Zeit bis zur Abgabe ist sehr eng bemessen. Auch Rückmeldungen hinsichtlich der Verständlichkeit sind sehr wertvoll. 

Fragen zum Projekt können direkt unter Issues gestellt werden.

Jeder, der sich für das Projekt interessiert ist zur Sitzung herzlich eingeladen. 

Viele Grüße
Arne Pfeilsticker

**Comment by hfhoyer** [comment]
... für den 16.2. entschuldige ich mich schon mal. Da bin ich nicht im Lande ...
Lokale Zeit ist 13:00h, da sammelt sich gerade mein Chor in der Hotelhalle.
