### ISSUE TITLE
Is "New Money Infrastructure" a good project title?

### ISSUE THREAD

**Issue by Arne-Pfeilsticker** [money-infrastructure/doku#15]
Florian rightly argues that what's "New" today is no longer "New" a few days later.

He proposes:
- INTEGRAL MONEY INFRASTRUCTURE
- HOLISTIC MONEY INFRASTRUCTURE
- MONEY INFRASTRUCTURE xyz
- INFRASTRUCTURE for qay
- MARKET INFRASTRUCTURE

Because of his suggestions, the following titles have crossed my mind:

- **Crypto Money Infrastructure** (Because it's a system that proves and provides ownership of money on cryptographically protected accounts. )
- **Crypto-Currency Infrastructure**
- **Creative Commons Money Infrastracture** (Because it is not a private property, but part of the creative commons (= schöpferisches Gemeingut)
- **Economic Commons Money Infrastructure** (Economic commons (= ökonomisches Gemeingut) would be a new term inspired by creative commons.)

The title gives the first impression and is therefore very important. Please help to find a good title.

**Comment by hfhoyer** [comment]
I would leave "crypto" out. Too much bad and ambiguous connotations.
"Creative Commons" sounds somehow more sympathetic, but points only to the licensing.
((But: "Commons" is a good approach. Money is a product of (parts of) the society to serve for a common purpose. Why should this be privatized? It should -at least in its paying functionality- be common good oriented. ))

- **Next Money Infrastructure** is better than NewMI. "Next" links both to Money and Infrastructure

**Comment by cedriccoiquaud** [comment]
Hi all,

I agree that « crypto » has connotations at the moment.
« Creative » could also be somewhat reductive, leaving a feeling of ephemeral hype ?
I like the energy of « Next Money Infrastructure », I’m just wary of the word « Infrastructure », which is quite technical ?

Some new ideas here:
NEXT DIME
DISTRIBUTED MONEY GRID
NEXT COMMONS
DEMOSOLIDUS (greek roots: Demos- people / -Solidus coin)

Kind regards
Cedric

PS. recap:
NEXT MONEY INFRASTRUCTURE

INTEGRAL MONEY INFRASTRUCTURE
HOLISTIC MONEY INFRASTRUCTURE
MONEY INFRASTRUCTURE xyz
INFRASTRUCTURE for qay
MARKET INFRASTRUCTURE

Crypto Money Infrastructure
Crypto-Currency Infrastructure
Creative Commons Money Infrastracture
Economic Commons Money Infrastructure

Cédric Coiquaud
+33.6.15.70.10.83
cedric.coiquaud@appi-conseil.com
skype: cedric_coiquaud

**Comment by hfhoyer** [comment]
![moneyplus](https://user-images.githubusercontent.com/32845439/35166606-b820c532-fd52-11e7-8104-532160da087d.PNG)

**Comment by klezmonaut** [comment]
# **TrueMoney Infrastructure**

Without Space between True and Money

**Comment by Arne-Pfeilsticker** [comment]
Could **Public Money Infrastructure** not be misunderstood to mean that it is an infrastructure for public money (= öffentliche Gelder)?

Could the misunderstanding be reduced by hyphenating it: Public **Money-Infrastructure**?

Or pick up Florian's idea and just: Money+Infrastructure
The plus sign written in Florian's style.

Or Public Infrastructure for Money+

Or Public domain Money Infrastructure

**Comment by Arne-Pfeilsticker** [comment]
Slowly we should come to a decision.

Unfortunately, we can not take Florian's proposal "Public Money Infrastructure" because the term "public money" means "money that has been collected by the state, usually through taxation".

Therefore, I suggest that we specify the following terms:
- Long name: "Public Infrastructure for Money and more"
- Alternatively: "Public Infrastructure for Money(+)" (the + sign as superscript in a circle)
- Short name: Money Infrastructure
- Abbreviation: PIM

If there are no objections, then I will change the texts accordingly.

**Comment by Arne-Pfeilsticker** [comment]
We discussed the topic at our last meeting of the Monetative in Frankfurt and  their the following adjectives were proposed:
- Open
- Free
- Mutual
- Common
- Public
- Common Market

The next day I discussed these suggestions again with Florian and a completely new term came up, expressing the intension very well:
- Co-op Money Infrastructure

The values associated with the [co-operative movment](https://ica.coop/en/whats-co-op/co-operative-identity-values-principles) are values that the money infrastructure strives, too.

**Comment by klezmonaut** [comment]
Hallo Arne. I gratulate to this new term! It ist a good choose. It evokes in me some frames as „win-win“ - „connecting people, bringing power together“ some social value for common interests.
 It’s a pity, that it wasn‘t possible to take „public“, but the new term „Co-op Money Infrastructure seems to me useful for a good campaigning, but I would take Hans suggestion with + in the word „Money“, because it could be a bridge referring to the „positive money“ term. 

If you find it necessary and helpful to invent and design some grafic expression, Logo, Pictogram or anything else, which could help to carry this issue better into public minds, please let me know.

I can layout some grafic examples for any purpose you need. Letters, Flyer, etc.
Here below some examples / only exercices I made. 
I wrote „coop“ without (-) but tried to divide it by colours, using the same colours of our monetative Logo to underline the connection to Vollgeld / Monetative.

Greetings 

Reiner Oberbeck
Kraichtal

![5ee90cef-d6f7-4e4f-99d6-19cee917cd84](https://user-images.githubusercontent.com/35613758/36115978-0742e7f4-1035-11e8-8a04-5789367e46ed.jpeg)

**Comment by Arne-Pfeilsticker** [comment]
Hi Reiner, I appreciate your commitment and would like to talk to you about the further course of action. Could you please contact me via Skype. My skype name is arne.pfeilsticker.

**Comment by klezmonaut** [comment]
Hallo Arne, 

Ich bin erst ab morgen Abend wieder zu Hause - gerne via Skype oder oder auch per Telefon - Passt es am Donnerstag ab ca 19 Uhr?
Oder irgendwann am Freitag - Samstag. 

Liebe Grüße aus dem Chiemgau

Reiner Oberbeck
Heidelsheimer Str. 11
76703 Kraichtal
07251-68433
0176-42686123
Reiner.oberbeck@posteo.de

Von meinem iPad gesendet

Am 14.02.2018 um 00:09 schrieb Arne Pfeilsticker <notifications@github.com>:

Hi Reiner, I appreciate your commitment and would like to talk to you about the further course of action. Could you please contact me via Skype. My skype name is arne.pfeilsticker.

**Comment by Arne-Pfeilsticker** [comment]
The name of the project I have set to "**Co-op Money Infrastructre**", because the co-operative nature of the project is a central feature.
