### ISSUE TITLE
Knowledge of the EU-Background of the proposal

### ISSUE THREAD

**Issue by hfhoyer** [money-infrastructure/doku#17]
I think, it's important to know the "landscape" where we are putting the proposal in.
The EU provides ample information for participants.

http://ec.europa.eu/research/participants/docs/h2020-funding-guide/grants/applying-for-funding/find-a-call_en.htm

http://ec.europa.eu/programmes/horizon2020/en/what-work-programme

https://ec.europa.eu/programmes/horizon2020/h2020-sections

This is the "overaching" document:
http://ec.europa.eu/programmes/horizon2020/sites/horizon2020/files/stratprog_overarching_version_for_publication.pdf
It contains interesting topics, we should refer to. E.g. the inclusion of stakeholders.
_The consultation of stakeholders in the widest sense has played an important part in the
strategic programming process for Work Programme 2018-20._ 

Here is a ZIP of all different work programmes:
http://ec.europa.eu/programmes/horizon2020/sites/horizon2020/files/17_thematic_papers.zip

Which would be the most appropriate "call" to connect to?
Is it "governance"? as the copied part in the proposal suggests?
IMHO: No. There are better ones.

Das ist auch noch wichtig:
http://ec.europa.eu/research/participants/data/ref/h2020/wp/2018-2020/main/h2020-wp1820-intro_en.pdf

**Comment by hfhoyer** [comment]
All open calls are listed here:
http://ec.europa.eu/research/participants/portal/desktop/en/opportunities/h2020/search/search_topics.html#c,topics=callStatus/t/Forthcoming/0/1/0/default-group&callStatus/t/Open/1/1/0/default-group&callStatus/t/Closed/0/1/0/default-group&+identifier/desc

**Comment by Arne-Pfeilsticker** [comment]
Hi Florian, I agree with you, it is most important that we connect to the right call.
Could you look through the calls and make a suggestion?

**Comment by hfhoyer** [comment]
Here is the report of my  looking through the calls of H2020 (link above)

[Horizon 2020.pdf](https://github.com/money-infrastructure/doku/files/1665996/Horizon.2020.pdf)
