### ISSUE TITLE
Stigmergy - a promising concept to organize the infrastructure?

### ISSUE THREAD

**Issue by hfhoyer** [money-infrastructure/doku#20]
... sorry, only avaiable in Geman.

[Stigmergie Infrastruktur.pdf](https://github.com/money-infrastructure/doku/files/2176220/Stigmergie.Infrastruktur.pdf)

**Comment by Arne-Pfeilsticker** [comment]
Hi Florian,
besten Dank für deinen sehr interessanten Ansatz und dein Engagement hinsichtlich der Projektorganisation. 

Könntest du bitte den Text in einer adoc-Datei im Ordner Deutsch speichen und einen Pull request aufmachen, damit dein Beitrag Teil des Projektes wird und eventuell auch durch andere bearbeitet werden kann. Wenn ich das mache, dann erscheit der Beitrag unter meinem Namen und ich möchte mich nicht mit fremden Federn schmücken.

Wenn du Hilfe bei der AsciiDoc-Formatierung benötigst, wirf einen Blick in das White Paper. Der etwas schwierigere Teil ist der Kopf, der Rest ist eine Markup-Variante. Hier der Link zum Handbuch: https://asciidoctor.org/docs/asciidoc-writers-guide/

**Comment by hfhoyer** [comment]
Hallo Arne,
es ist mit zu zeitaufwendig, die Enviroments zu installieren und mich einzuarbeiten. Sieh mir das bitte nach und tue Du es. Du kannst ja einen Vermerk voranstellen, dass Du das aus dem Issue von mir genommen hast.
