### ISSUE TITLE
Hashgraph statt Blockchain

### ISSUE THREAD

**Issue by ghost** [money-infrastructure/doku#6]
deleted

**Comment by Arne-Pfeilsticker** [comment]
Antwort zu Frage 1:
Es gibt keine technische Überschneidung. Die anstehenden Probleme werden auf eine "erschreckend" einfache Art und Weise gelöst. Hier die zentralen Ideen:

Jeder Nutzer hat einen eigenen Blockchain-Baum, in dem die Verträge und Transaktionen eines Nutzers gespeichert werden. Dieser Baum wird auf der Hardware des Nuters gespeichert und mindestens drei verschlüsselte Backups werden bei anderen Nutzern gespeichert. Die einzelnen Blockchains sind vergleichbar mit Konten einer Buchhaltung. Ein einzelner Block besteht aus den Transaktionen, die ein Nuter in einem Arbeitsgang ausführt. Der letzte Eintrag ist immer der Saldovortag des Kontos.

Es gibt einen gemeinsamen Identitäten-Blockchain-Baum (IBB), der auf einem verteilten Multimaster-Server-Cluster läuft, an dem sich die Nutzer registrieren. Die Identitäten Blockchain eines Nutzers im IBB speichert auch die Blockhashs der Nutzer-Blockchains, um prüfen zu können, ob eventuell eine Blockchain beim Nutzer manipuliert oder beschädigt wurde. Falls ja, wird der lokale Blockchain-Baum aus den Sicherungen wieder hergestellt.

Die Verknüpfung eines Blocks mit dem Hash aus dem vorigen Block wird nur benutzt, um effizient die Integrität einer Blockchain zu prüfen. Eine Nonce und target dificulty gibt es nicht.

Damit ein Nutzer kein Interesse hat seine Daten zu manipulieren habe ich das sog. inverse Konsensieren entwicklet. Dabei wird das auf den ersten Blick sehr schwierige Problem auf der rechtlichen Ebene gelöst. Die Idee stammt von den Wertpapieren. Bei einem Wertpapier wird das Recht aus dem Papier mit dem Recht am Papier, derartig verknüpft, dass das Recht nicht ohne das Papier geltend gemacht werden kann.

Beim inversen Konsensieren werden nur die Vertragsparteien benötigt und das Papier wird durch eineindeutige Daten ersetzt. Der Effekt ist, dass wenn ein Nutzer seine Daten manipuliert, dann wäre das so, wie wenn er seinen eigenen Tressor mit seinem ganzen Geld in die Luft sprengt. Sicher keine gute Idee. Siehe Grafik.
![gip013](https://user-images.githubusercontent.com/2308228/34221412-38baf508-e5b8-11e7-98be-040b544f2b1b.png)

Frage 2: Juristen ja, ob Patentanwalt weiß ich nicht.

Frage 3: Ich wüsste noch nicht, welche Ideen ich übernehmen sollte, da das von mir vorgeschlagene Verfahren erheblich einfacher und effizienter ist.
