### ISSUE TITLE
Technische Spezifikation der Geldinfrastruktur / Whitepaper

### ISSUE THREAD

**Issue by ghost** [money-infrastructure/doku#7]
deleted

**Comment by Arne-Pfeilsticker** [comment]
In meinem Buch werden die theoretischen Grundlagen gelegt. Am Whitepaper arbeite ich und denke, dass es im Zuge der Erarbeitung des Antrags fertig wird.

Das Whitepaper wird dann in der Projektdokumentation erscheinen.
