### ISSUE TITLE
Open source - welche Lizenz?

### ISSUE THREAD

**Issue by ghost** [money-infrastructure/doku#8]
deleted

**Comment by Arne-Pfeilsticker** [comment]
Das ist noch nicht entschieden. Vielleicht MIT - Finanzsektor + ethische Banken. :-)
Hast du einen Vorschlag?

**Comment by Paul-Zehle** [comment]
So tief in die rechtliche Materie bin ich bisher nicht eingetaucht.

So weit ich weiß, ist man alleine schon durch die Integration anderer Open-Source-Software zur Übernahme der jeweiligen Lizenz gezwungen.

Daraus ergeben sich Fragen wie:
- Ist es rechtlich möglich das Geldinfrastruktur-Projekt unter eine andere Lizenz zu stellen, wenn Teile davon open-source-Software beinhaltet, die einer anderen Lizenz unterliegt?
- Sollte man das Projekt eventuell aufsplitten, um den rechtlichen Erfordernissen der verschiedenen Lizenzen besser gerecht zu werden?
- Gibt es eine hierarchische Struktur der open-source-Lizenzen?
- Gibt es open-source-Lizenzen, die von vornherein ausgeschlossen werden, welche Kriterien könnten das sein?
- Ist es rechtlich möglich eine Lizenz zu erweitern, um die Nutzung durch bestimmte Geschäfts-
 oder Investitionsbanken auszuschließen oder müsste man dazu eine eigene aufsetzen?

Diese Fragen übersteigen meine Expertise. Ich denke zur Klärung kommen wir um eine Rechtsberatung nicht herum. Vielleicht gibt es ja patentrechtliche Hilfevereine, die wir in Anspruch nehmen können?

Ist das Thema für den Meilenstein "Förderantrag" überhaupt relevant oder könnten wir das erstmal ins Backlog schieben und uns später darum kümmern?

**Comment by serapath** [comment]
+1 MIT
Je weniger Zeit vergeudet wird über Lizenzen nachzudenken, desto besser.

**Comment by Paul-Zehle** [comment]
Eine MIT-Lizenz scheint zielführend zu sein.

Hier gibt es eine umfassende Erläuterung zu dem Thema:
https://www.bitkom.org/noindex/Publikationen/2016/Leitfaden/Open-Source-Software-20/FirstSpirit-1498131485664160229-OSS-Open-Source-Software.pdf

Inwiefern man die Nutzung einschränken kann und sollte, lasse ich jetzt mal offen.
