### ISSUE TITLE
Projektarbeit, Projektstruktur, Meilensteine, Labels, Todos, Wiki ...

### ISSUE THREAD

**Issue by ghost** [money-infrastructure/doku#9]
deleted

**Comment by Arne-Pfeilsticker** [comment]
Hallo Paul, diese Fragen werden Gegenstand der nächsten Arbeitssitzungen sein. - Aber für jede Vorarbeit in dieser Richtung, wäre ich dir sehr dankbar.

**Comment by serapath** [comment]
1. Diskussion in Issues
2. Pull Requests für Änderungen die dann diskutiert und gemerged werden.

Je weniger Umstand, desto besser.

Ich bin dafür, dass Arne BDFL (Benevolent Dictator for Life) ist und das letzte Wort hat.
Wer nicht einverstanden ist kann das Projekt FORKEN oder woanders hingehen.

**Comment by hfhoyer** [comment]
Serapath, der Vorschlag zur Arbeitsweise scheint dem Projekt nicht angemessen. 
Wenn die geplante Infrastruktur ohne Dictator -wie benevolent auch immer- auskommen soll,
muß es die Vorartbeit dazu auch. Wenn die Vorarbeit nicht den proof of work dafür bringt, ist
die Arbeit an einer Struktur, die es bringen soll, ein benevolenter Fake.
> Wer nicht einverstanden ist kann das Projekt FORKEN oder woanders hingehen.

Ist ein guter Vorschlag, wenn er für alle gilt.
